replace ci matrix strategy with single jobs

diff --git a/.github/workflows/auto-deploy.yml b/.github/workflows/auto-deploy.yml
--- a/.github/workflows/auto-deploy.yml
+++ b/.github/workflows/auto-deploy.yml
@@ -8,34 +8,24 @@ on:
     - cron: "0 8 * * *"
 
 jobs:
-  define-matrix:
-    runs-on: ci-ocf-nix-deploy
-    outputs:
-      hosts: ${{ steps.hosts.outputs.hosts }}
-    steps:
-      - uses: actions/checkout@v4
-      - id: hosts
-        run: echo "hosts=$(nix eval .#automatedDeployNodes --json)" >> "$GITHUB_OUTPUT"
-
   deploy:
     runs-on: ci-ocf-nix-deploy
-    needs: define-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        host: ${{ fromJSON(needs.define-matrix.outputs.hosts) }}
     steps:
       - uses: actions/checkout@v4
+
+      - name: Setup hosts
+        run: |
+          HOSTS=$(nix eval .#automatedDeployNodes --apply 'builtins.concatStringsSep " "' --raw)
+          echo "HOSTS=$HOSTS" >> $GITHUB_ENV
 
       - name: Setup SSH
         run: |
           echo '${{ secrets.COLMENA_APPLY_SSH_KEY }}' > ${{ github.workspace }}/id_ed25519
-          chmod 400 ${{ github.workspace }}/id_ed25519
+          chmod 400 id_ed25519
 
-          keyfile=${{ github.workspace }}/secrets/host-keys/${{ matrix.host }}.pub
-          fqdn="${{ matrix.host }}.ocf.berkeley.edu"
-          pubkey=$(cat "$keyfile")
-          echo "$fqdn $pubkey" >> ${{ github.workspace }}/known_hosts
+          for host in $HOSTS; do
+            cat secrets/host-keys/$host.pub | sed "s/^/$host.ocf.berkeley.edu /" >> known_hosts
+          done
 
           echo "
           Identityfile $GITHUB_WORKSPACE/id_ed25519
@@ -47,15 +37,15 @@ jobs:
       - name: Deploy with colmena
         env:
           SSH_CONFIG_FILE: ${{ github.workspace }}/ssh_config
-        run: nix develop .#deploy -c colmena apply --on ${{ matrix.host }} switch >> ${{ matrix.host }}.log 2>&1
-
-      - name: Display log
-        if: always()
-        run: cat ${{ matrix.host }}.log
-
-  check-all-hosts:
-    runs-on: ci-ocf-nix-deploy
-    needs: deploy 
-    steps:
-      - name: Combined GitHub status check
-        run: echo "All hosts deployed successfully!"
+        run: |
+          echo "$HOSTS" | tr ' ' '\n' | \
+          xargs -P 10 -n 1 -I {} \
+          sh -c "
+            if nix develop .#deploy -c colmena apply --on {} switch > {}.log 2>&1; then
+              echo '✅ Successfully deployed to {}'
+            else
+              echo '❌ Failed to deploy to {}'
+              cat {}.log
+              exit 1
+            fi
+          "
